# Generated by Django 5.2.6 on 2025-09-17 22:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Nom complet de l'auteur", max_length=100, verbose_name="Nom de l'auteur")),
                ('biographie', models.TextField(blank=True, help_text='Brève biographie')),
                ('date_naissance', models.DateField(blank=True, help_text='Date de naissance de l’auteur', null=True)),
                ('email', models.EmailField(blank=True, help_text='Email de l’auteur', max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID unique')),
                ('titre', models.CharField(db_index=True, help_text='Titre officiel du livre', max_length=200, verbose_name='Titre du livre')),
                ('slug', models.SlugField(help_text='Version url-friendly du titre', unique=True)),
                ('description', models.TextField(blank=True, help_text='Résumé ou description')),
                ('date_publication', models.DateField(blank=True, help_text='Date de publication', null=True)),
                ('couverture', models.ImageField(blank=True, help_text='Image de couverture', null=True, upload_to='couvertures/')),
                ('disponible', models.BooleanField(default=True, help_text='Disponibilité pour le prêt')),
                ('prix', models.DecimalField(decimal_places=2, default=0.0, help_text="Prix d'achat en €", max_digits=7)),
                ('isbn', models.CharField(help_text='Code ISBN du livre', max_length=20, unique=True)),
                ('fichier_pdf', models.FileField(blank=True, help_text='Version PDF du livre', null=True, upload_to='livres/pdf/')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livres', to='mybook.auteur', verbose_name='Auteur principal')),
                ('co_auteurs', models.ManyToManyField(blank=True, related_name='livres_coauteur', to='mybook.auteur', verbose_name='Co-auteurs')),
            ],
        ),
    ]
