# Generated by Django 5.1.3 on 2025-09-17 13:50

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID unique pour chaque produit. Non modifiable après la création.', primary_key=True, serialize=False, unique=True, verbose_name="ID de l'article")),
                ('name', models.CharField(db_comment='Nom unique du produit.', max_length=200, unique=True, verbose_name='Nom du produit')),
                ('slug', models.SlugField(help_text="Chaîne de caractères pour une URL unique et lisible par l'homme.", max_length=250, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description complète du produit.', null=True, verbose_name='Description')),
                ('category', models.CharField(choices=[('ELECTRONICS', 'Électronique'), ('CLOTHING', 'Vêtements'), ('BOOKS', 'Livres'), ('FOOD', 'Alimentation')], db_index=True, default='ELECTRONICS', help_text='Catégorie du produit.', max_length=50, verbose_name='Catégorie')),
                ('is_available', models.BooleanField(default=True, help_text='Indique si le produit est en stock.')),
                ('stock', models.IntegerField(help_text='Nombre de produits en stock. Ne peut pas être négatif.', validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.DecimalField(decimal_places=2, help_text='Prix du produit. Max 10 chiffres, 2 décimales.', max_digits=10)),
                ('release_date', models.DateField(blank=True, help_text='Date de sortie du produit.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date et heure de la création du produit.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière mise à jour.')),
                ('image', models.ImageField(blank=True, help_text='Image du produit.', null=True, upload_to='products/')),
                ('parent_product', models.ForeignKey(blank=True, help_text='Produit parent pour les variations de couleur ou de taille.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variations', to='myapp.product')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'db_table': 'myproject_products',
                'ordering': ['name'],
                'unique_together': {('name', 'category')},
            },
        ),
    ]
